apiVersion: v1
kind: Service
metadata:
  labels:
    app: dp2
  name: dp2svc
spec:
  ports:
  - port: 8040
    protocol: TCP
    targetPort: 8040
    nodePort: 30001
  selector:
    app: dp2
  type: NodePort
